### PR TITLE
rebase to noble

### PR DESCRIPTION
**Pull request by drizuid**
rebase to noble now that CW officially supports python 3.12

### CODE REVIEW

**Comment by aptalca** [comment]
looks like `libldap-2.5-0` package is just `libldap2` in noble

**Comment by drizuid** [comment]
> looks like `libldap-2.5-0` package is just `libldap2` in noble

yah was just seeing that 
image

**Comment by drizuid** [comment]
pending validation of arm64 due to failed smoketest

**Comment by mgrimace** [comment]
Test results: good, no issues 
Hardware: arm64
Tests conducted, using docker compose:
- created and started calibre to create initial calibre database
- created and started calibre-web using `ghcr.io/linuxserver/lspipepr-calibre-web:0.6.24-PR-333` tag
- logged in with default account, browsed calibre-web webUI
- set up admin account, pointed to calibre library
- all basic functions appear to work as expected, no errors encountered

**Review by thespad — APPROVED** [review]

**Pull request merged**
