### PR TITLE
Kindlegen

### PR DESCRIPTION
**Pull request by CHBMB**
Adds kindlegen support.

### CODE REVIEW

**Comment by CHBMB** [comment]
@sparklyballs Changed it to check to see if kindlegen is already in `/app/calibre-web/vendor` I really don't think the version is a problem as it hasn't changed for nearly half a decade.....

**Comment by sparklyballs** [comment]
it's also 386 so won't work on 64 bit only hosts

i don't think this should be added even in this form

**Comment by CHBMB** [comment]
@sparklyballs It does work on x64 hosts.  As long as they have IA32 in kernel it works fine, tested it on Ubuntu and Unraid v6.3.5 and v6.4.0 

Only one it didn't work on was Unraid v6.3.5 as it doesn't have IA32.

**Comment by sparklyballs** [comment]
unraid is not the only host that is 64 bit only

**Pull request closed without merging**
