### PR TITLE
Add package libllvm11

### PR DESCRIPTION
**Pull request by zetneteork**
## Description:
Add missing package

## Benefits of this PR and context:
Fix dependency

## How Has This Been Tested?
Local build

### CODE REVIEW

**Comment by drizuid** [comment]
what is this needed for?

**Review by drizuid — COMMENTED** [review]
Can you please clarify what adding this dependency resolves or adds?

**Comment by drizuid** [comment]
closing this as libllvm11 is installed naturally as a dependency
```
2021-06-25T21:48:43.293709473Z 6 packages can be upgraded. Run 'apt list --upgradable' to see them.
2021-06-25T21:48:43.298189104Z
2021-06-25T21:48:43.298208587Z WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
2021-06-25T21:48:43.298214800Z
2021-06-25T21:48:44.180845674Z Reading package lists...
2021-06-25T21:48:44.338890369Z Building dependency tree...
2021-06-25T21:48:44.339094587Z Reading state information...
2021-06-25T21:48:44.488176734Z The following additional packages will be installed:
2021-06-25T21:48:44.488217705Z   libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
2021-06-25T21:48:44.488228567Z   libdrm2 libedit2 libelf1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0
2021-06-25T21:48:44.488803416Z   libglx-mesa0 libglx0 libllvm11 libpciaccess0 libsensors-config libsensors5
2021-06-25T21:48:44.488827437Z   libvulkan1 libwayland-client0 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0
2021-06-25T21:48:44.488833693Z   libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-sync1 libxcb-xfixes0
2021-06-25T21:48:44.489001789Z   libxdamage1 libxfixes3 libxshmfence1 libxxf86vm1 mesa-vulkan-drivers
```

**Comment by zetneteork** [comment]
Due to the dependencies there are troubles with `libgl1-mesa-glx` and `libgl1-mesa-dri`

```bash
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
libgl1-mesa-glx is already the newest version (20.2.6-0ubuntu0.20.04.1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libgl1-mesa-dri : Depends: libllvm11 (>= 1:9~svn298832-1~) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

```bash
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
/var/run/s6/etc/cont-init.d/60-calibre-config: line 4: /app/calibre/calibre_postinstall: cannot execute binary file: Exec format error

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [101 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [995 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [921 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse arm64 Packages [7,384 B]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal-security/main arm64 Packages [601 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal-security/universe arm64 Packages [668 kB]
Fetched 3,520 kB in 8s (416 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
24 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
libgl1-mesa-glx is already the newest version (20.2.6-0ubuntu0.20.04.1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libgl1-mesa-dri : Depends: libllvm11 (>= 1:9~svn298832-1~) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
[cont-init.d] 60-calibre-config: exited 100.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by zetneteork** [comment]
## Docker Compose

```yaml
---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /data/docker/calibre-web/config:/config
      - /data/docker/calibre-web/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

## Log output
```
[mod-init] Curl/JQ was not found on this system for Docker mods installing
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [101 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 Packages [11.1 MB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal/restricted arm64 Packages [1,317 B]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 Packages [1,234 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/multiverse arm64 Packages [139 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted arm64 Packages [2,893 B]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [1,025 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse arm64 Packages [7,363 B]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [970 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe arm64 Packages [4,304 B]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal-security/universe arm64 Packages [715 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse arm64 Packages [2,378 B]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal-security/main arm64 Packages [627 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted arm64 Packages [2,649 B]
Fetched 16.4 MB in 15s (1,082 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.5).
The following additional packages will be installed:
  libjq1 libonig5
The following NEW packages will be installed:
  jq libjq1 libonig5
0 upgraded, 3 newly installed, 0 to remove and 6 not upgraded.
Need to get 291 kB of archives.
After this operation, 1,022 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 libonig5 arm64 6.9.4-1 [134 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 libjq1 arm64 1.6-1ubuntu0.20.04.1 [107 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 jq arm64 1.6-1ubuntu0.20.04.1 [49.6 kB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/aarch64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/aarch64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 3.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 291 kB in 1s (281 kB/s)
Selecting previously unselected package libonig5:arm64.
(Reading database ... 11930 files and directories currently installed.)
Preparing to unpack .../libonig5_6.9.4-1_arm64.deb ...
Unpacking libonig5:arm64 (6.9.4-1) ...
Selecting previously unselected package libjq1:arm64.
Preparing to unpack .../libjq1_1.6-1ubuntu0.20.04.1_arm64.deb ...
Unpacking libjq1:arm64 (1.6-1ubuntu0.20.04.1) ...
Selecting previously unselected package jq.
Preparing to unpack .../jq_1.6-1ubuntu0.20.04.1_arm64.deb ...
Unpacking jq (1.6-1ubuntu0.20.04.1) ...
Setting up libonig5:arm64 (6.9.4-1) ...
Setting up libjq1:arm64 (1.6-1ubuntu0.20.04.1) ...
Setting up jq (1.6-1ubuntu0.20.04.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
/var/run/s6/etc/cont-init.d/60-calibre-config: line 4: /app/calibre/calibre_postinstall: cannot execute binary file: Exec format error

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Reading package lists...
Building dependency tree...
Reading state information...
6 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libelf1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0
  libllvm11 libsensors-config libsensors5 libx11-xcb1 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1 libxcb-xfixes0
  libxdamage1 libxfixes3 libxshmfence1 libxxf86vm1
Suggested packages:
  lm-sensors
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libelf1 libgl1 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libllvm11 libsensors-config libsensors5 libx11-xcb1
  libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1
  libxcb-xfixes0 libxdamage1 libxfixes3 libxshmfence1 libxxf86vm1
0 upgraded, 28 newly installed, 0 to remove and 6 not upgraded.
Need to get 21.7 MB of archives.
After this operation, 709 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libelf1 arm64 0.176-1.1build1 [44.2 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libdrm-common all 2.4.102-1ubuntu1~20.04.1 [5,388 B]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libdrm2 arm64 2.4.102-1ubuntu1~20.04.1 [32.1 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libedit2 arm64 3.1-20191231-1 [82.7 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libdrm-amdgpu1 arm64 2.4.102-1ubuntu1~20.04.1 [17.7 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libdrm-nouveau2 arm64 2.4.102-1ubuntu1~20.04.1 [15.7 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libdrm-radeon1 arm64 2.4.102-1ubuntu1~20.04.1 [18.7 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libglapi-mesa arm64 20.2.6-0ubuntu0.20.04.1 [36.1 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libllvm11 arm64 1:11.0.0-2~ubuntu20.04.1 [14.5 MB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libsensors-config all 1:3.6.0-2ubuntu1 [6,092 B]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libsensors5 arm64 1:3.6.0-2ubuntu1 [26.1 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libgl1-mesa-dri arm64 20.2.6-0ubuntu0.20.04.1 [6,533 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libglvnd0 arm64 1.3.2-1~ubuntu0.20.04.1 [42.5 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libx11-xcb1 arm64 2:1.6.9-2ubuntu1.2 [9,380 B]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxcb-dri2-0 arm64 1.14-2 [6,872 B]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxcb-dri3-0 arm64 1.14-2 [6,556 B]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxcb-glx0 arm64 1.14-2 [22.1 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxcb-present0 arm64 1.14-2 [5,484 B]
Get:19 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxcb-sync1 arm64 1.14-2 [8,824 B]
Get:20 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxcb-xfixes0 arm64 1.14-2 [9,268 B]
Get:21 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxdamage1 arm64 1:1.1.5-2 [6,820 B]
Get:22 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxfixes3 arm64 1:5.0.3-2 [10.8 kB]
Get:23 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxshmfence1 arm64 1.3-1 [4,868 B]
Get:24 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libxxf86vm1 arm64 1:1.1.4-1build1 [9,908 B]
Get:25 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libglx-mesa0 arm64 20.2.6-0ubuntu0.20.04.1 [143 kB]
Get:26 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libglx0 arm64 1.3.2-1~ubuntu0.20.04.1 [29.6 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libgl1 arm64 1.3.2-1~ubuntu0.20.04.1 [88.5 kB]
Get:28 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libgl1-mesa-glx arm64 20.2.6-0ubuntu0.20.04.1 [5,540 B]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 28.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/aarch64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/aarch64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 28.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 21.7 MB in 7s (3,043 kB/s)
Selecting previously unselected package libelf1:arm64.
(Reading database ... 11947 files and directories currently installed.)
Preparing to unpack .../00-libelf1_0.176-1.1build1_arm64.deb ...
Unpacking libelf1:arm64 (0.176-1.1build1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../01-libdrm-common_2.4.102-1ubuntu1~20.04.1_all.deb ...
Unpacking libdrm-common (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libdrm2:arm64.
Preparing to unpack .../02-libdrm2_2.4.102-1ubuntu1~20.04.1_arm64.deb ...
Unpacking libdrm2:arm64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libedit2:arm64.
Preparing to unpack .../03-libedit2_3.1-20191231-1_arm64.deb ...
Unpacking libedit2:arm64 (3.1-20191231-1) ...
Selecting previously unselected package libdrm-amdgpu1:arm64.
Preparing to unpack .../04-libdrm-amdgpu1_2.4.102-1ubuntu1~20.04.1_arm64.deb ...
Unpacking libdrm-amdgpu1:arm64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libdrm-nouveau2:arm64.
Preparing to unpack .../05-libdrm-nouveau2_2.4.102-1ubuntu1~20.04.1_arm64.deb ...
Unpacking libdrm-nouveau2:arm64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libdrm-radeon1:arm64.
Preparing to unpack .../06-libdrm-radeon1_2.4.102-1ubuntu1~20.04.1_arm64.deb ...
Unpacking libdrm-radeon1:arm64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libglapi-mesa:arm64.
Preparing to unpack .../07-libglapi-mesa_20.2.6-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libglapi-mesa:arm64 (20.2.6-0ubuntu0.20.04.1) ...
Selecting previously unselected package libllvm11:arm64.
Preparing to unpack .../08-libllvm11_1%3a11.0.0-2~ubuntu20.04.1_arm64.deb ...
Unpacking libllvm11:arm64 (1:11.0.0-2~ubuntu20.04.1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-folyZj/08-libllvm11_1%3a11.0.0-2~ubuntu20.04.1_arm64.deb (--unpack):
 error setting ownership of './usr/lib/aarch64-linux-gnu/libLLVM-11.so.1': Device or resource busy
Selecting previously unselected package libsensors-config.
Preparing to unpack .../09-libsensors-config_1%3a3.6.0-2ubuntu1_all.deb ...
Unpacking libsensors-config (1:3.6.0-2ubuntu1) ...
Selecting previously unselected package libsensors5:arm64.
Preparing to unpack .../10-libsensors5_1%3a3.6.0-2ubuntu1_arm64.deb ...
Unpacking libsensors5:arm64 (1:3.6.0-2ubuntu1) ...
Selecting previously unselected package libgl1-mesa-dri:arm64.
Preparing to unpack .../11-libgl1-mesa-dri_20.2.6-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libgl1-mesa-dri:arm64 (20.2.6-0ubuntu0.20.04.1) ...
Selecting previously unselected package libglvnd0:arm64.
Preparing to unpack .../12-libglvnd0_1.3.2-1~ubuntu0.20.04.1_arm64.deb ...
Unpacking libglvnd0:arm64 (1.3.2-1~ubuntu0.20.04.1) ...
Selecting previously unselected package libx11-xcb1:arm64.
Preparing to unpack .../13-libx11-xcb1_2%3a1.6.9-2ubuntu1.2_arm64.deb ...
Unpacking libx11-xcb1:arm64 (2:1.6.9-2ubuntu1.2) ...
Selecting previously unselected package libxcb-dri2-0:arm64.
Preparing to unpack .../14-libxcb-dri2-0_1.14-2_arm64.deb ...
Unpacking libxcb-dri2-0:arm64 (1.14-2) ...
Selecting previously unselected package libxcb-dri3-0:arm64.
Preparing to unpack .../15-libxcb-dri3-0_1.14-2_arm64.deb ...
Unpacking libxcb-dri3-0:arm64 (1.14-2) ...
Selecting previously unselected package libxcb-glx0:arm64.
Preparing to unpack .../16-libxcb-glx0_1.14-2_arm64.deb ...
Unpacking libxcb-glx0:arm64 (1.14-2) ...
Selecting previously unselected package libxcb-present0:arm64.
Preparing to unpack .../17-libxcb-present0_1.14-2_arm64.deb ...
Unpacking libxcb-present0:arm64 (1.14-2) ...
Selecting previously unselected package libxcb-sync1:arm64.
Preparing to unpack .../18-libxcb-sync1_1.14-2_arm64.deb ...
Unpacking libxcb-sync1:arm64 (1.14-2) ...
Selecting previously unselected package libxcb-xfixes0:arm64.
Preparing to unpack .../19-libxcb-xfixes0_1.14-2_arm64.deb ...
Unpacking libxcb-xfixes0:arm64 (1.14-2) ...
Selecting previously unselected package libxdamage1:arm64.
Preparing to unpack .../20-libxdamage1_1%3a1.1.5-2_arm64.deb ...
Unpacking libxdamage1:arm64 (1:1.1.5-2) ...
Selecting previously unselected package libxfixes3:arm64.
Preparing to unpack .../21-libxfixes3_1%3a5.0.3-2_arm64.deb ...
Unpacking libxfixes3:arm64 (1:5.0.3-2) ...
Selecting previously unselected package libxshmfence1:arm64.
Preparing to unpack .../22-libxshmfence1_1.3-1_arm64.deb ...
Unpacking libxshmfence1:arm64 (1.3-1) ...
Selecting previously unselected package libxxf86vm1:arm64.
Preparing to unpack .../23-libxxf86vm1_1%3a1.1.4-1build1_arm64.deb ...
Unpacking libxxf86vm1:arm64 (1:1.1.4-1build1) ...
Selecting previously unselected package libglx-mesa0:arm64.
Preparing to unpack .../24-libglx-mesa0_20.2.6-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libglx-mesa0:arm64 (20.2.6-0ubuntu0.20.04.1) ...
Selecting previously unselected package libglx0:arm64.
Preparing to unpack .../25-libglx0_1.3.2-1~ubuntu0.20.04.1_arm64.deb ...
Unpacking libglx0:arm64 (1.3.2-1~ubuntu0.20.04.1) ...
Selecting previously unselected package libgl1:arm64.
Preparing to unpack .../26-libgl1_1.3.2-1~ubuntu0.20.04.1_arm64.deb ...
Unpacking libgl1:arm64 (1.3.2-1~ubuntu0.20.04.1) ...
Selecting previously unselected package libgl1-mesa-glx:arm64.
Preparing to unpack .../27-libgl1-mesa-glx_20.2.6-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libgl1-mesa-glx:arm64 (20.2.6-0ubuntu0.20.04.1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-folyZj/08-libllvm11_1%3a11.0.0-2~ubuntu20.04.1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
[cont-init.d] 60-calibre-config: exited 100.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

**Pull request closed without merging**
